### ISSUE TITLE
Symetrical template

### ISSUE THREAD

**Issue by qchatenet** [pibooth/pibooth-picture-template#4]
Hi,
Is it possible to create a symetrical template as shown in the following picture ? Photos would be the same in the 2 columns. The main idea is to be able to cut the 4*6 print in two to share between guests (and reproduce a strip photo style).
![template_sym](https://user-images.githubusercontent.com/42297011/100324790-00e67500-2fc8-11eb-8fe0-16f428cd543d.JPG)

**Comment by werdeil** [comment]
Hi @qchatenet,

For now I don't think this is possible, but maybe you can create a template for the left part and use the option `pictures_per_page` in the pibooth config to have it duplicated after.

I haven't tested it and I don't have access to a setup to test it right now but tell us if this is a solution for you.

**Comment by anxuae** [comment]
Hi @qchatenet , can you tel us if the solution given by @werdeil (use of `pictures_per_page`) is working well?
If yes, can you close this issue?

Thanks

**Comment by uncle-buzz** [comment]
Hi,
I didn't try this option myself, but to my mind, it would be better to link this option to the template, because your option is set for all the prints if I understood correctly how it works.
This ability to "clone" a print on a template could be great to keep a copy for the guests, and a copy for the host in a golden book without using 2 prints and a full-size print in the golden book.
To my mind, the best way would be to be able to print many times the same raw picture as requested here https://github.com/pibooth/pibooth-picture-template/issues/8 and build a symmetrical template.
